export default () => ({
    date: ["1398/01/01", "1398/12/29"],
    hasLoadedFilters: false,
    removedFilterIds: [],
    hasComparsion: false,
    comparisonDetail: null,
    details: [{
        id: 0,
        label: "استان",
        englishLabel: "province",
        inputType: "select",
        value: null,
        options: [],
    },
    {
        id: 1,
        label: "منبع دریافت پیام",
        englishLabel: "infoSource",
        inputType: "select",
        value: null,
        options: [],
    },
    {
        id: 2,
        label: "وسیله دریافت پیام",
        englishLabel: "infoDevice",
        inputType: "select",
        value: null,
        options: [],
    },
    {
        id: 3,
        label: "تعداد مجروحان هر تصادف",
        englishLabel: "injuredCount",
        inputType: "number",
        value: null,
    },
    {
        id: 4,
        label: "تعداد فوتی‌های هر تصادف",
        englishLabel: "deadCount",
        inputType: "number",
        value: null,
    },
    {
        id: 5,
        label: "تعداد وسایل در هر تصادف",
        englishLabel: "vehicleCount",
        inputType: "number",
        value: null,
    },
    {
        id: 6,
        label: "انواع وسایل در هر تصادف",
        englishLabel: "vehicleType",
        inputType: "select",
        value: null,
        options: [],
    },
    {
        id: 7,
        label: "انواع برخورد",
        englishLabel: "incidentType",
        inputType: "select",
        value: null,
        options: [],
    },
    {
        id: 8,
        label: "شکل برخورد",
        englishLabel: "incidentPart",
        inputType: "select",
        value: null,
        options: [],
    },
    {
        id: 9,
        label: "علت تامه تصادف",
        englishLabel: "incidentReason",
        inputType: "select",
        value: null,
        options: [],
    }]
})