export default () => ({
    date: ["1400/01/01", "1400/03/31"],
    hasLoadedFilters: false,
    provinceSelected: null,
    infoSourceSelected: null,
    infoDeviceSelected: null,
    injuriesCountSelected: null,
    deadCountSelected: null,
    vehicleCountSelected: null,
    vehicleTypeSelected: null,
    incidentTypeSelected: null,
    incidentPartSelected: null,
    incidentReasonSelected: null,
    provinces: [],
    infoSources: [],
    infoDevices: [],
    vehicleTypes: [],
    incidentTypes: [],
    incidentParts: [],
    incidentReasons: [],
    removedFilterIds: [],
})